src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Table("user")
 * @ORM\Entity
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     * @Assert\NotBlank(message="Vous devez saisir un nom d'utilisateur.")
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=60, unique=true)
     * @Assert\NotBlank(message="Vous devez saisir une adresse email.")
     * @Assert\Email(message="Le format de l'adresse n'est pas correcte.")
     */
    private $email;

    public function getId()
    {
        return $this->id;
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function getSalt()
    {
        return null;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;
    }

    public function getRoles()
    {
        return array('ROLE_USER');
    }

    public function eraseCredentials()
    {
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Application de gestion des tâches">
        <meta name="author" content="To Do List app">

        <title>To Do List app</title>

        <link rel="shortcut icon" href="{{ asset('assets/favicon.ico') }}"  />

        <!-- Bootstrap Core CSS -->
        <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ asset('assets/css/shop-homepage.css') }}" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <nav class="navbar navbar-light navbar-fixed-top" style="background-color: #e3f2fd;" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ path('homepage') }}">To Do List app</a>

                    <img src="{{ asset('assets/img/Logo_OpenClassrooms.png') }}" alt="OpenClassrooms" />
                </div>
            </div>
        </nav>

        <!-- Page Content -->
        <div class="container">
            <div class="row">

                {% if 'homepage' != app.request.attributes.get('_route') %}
                    <a href="{{ path('homepage') }}" class="btn btn-success">Accueil</a>
                {% endif %}

                {% if app.user and app.user.roles == ['ROLE_ADMIN'] and 'user_create' != app.request.attributes.get('_route') %}
                    <a href="{{ path('user_create') }}" class="btn btn-primary">Créer un utilisateur</a>
                {% endif %}

                {% if app.user and app.user.roles == ['ROLE_ADMIN'] and 'user_list' != app.request.attributes.get('_route') %}
                    <a href="{{ path('user_list') }}" class="btn btn-info">Consulter la liste des utilisateurs</a>
                {% endif %}

                {% if app.user %}
                <a href="{{ path('logout') }}" class="pull-right btn btn-danger">Se déconnecter</a>
                {% endif %}

                {% if not app.user and 'login' != app.request.attributes.get('_route') %}
                <a href="{{ path('login') }}" class="btn btn-success">Se connecter</a>
                {% endif %}
            </div>

            <div class="row">
                <div class="col-md-12">
                    {% for flash_message in app.session.flashBag.get('success') %}
                        <div class="alert alert-success" role="alert">
                            <strong>Superbe !</strong> {{ flash_message }}
                        </div>
                    {% endfor %}

                    {% for flash_message in app.session.flashBag.get('error') %}
                        <div class="alert alert-danger" role="alert">
                            <strong>Oops !</strong> {{ flash_message }}
                        </div>
                    {% endfor %}

                    {% block header_title %}{% endblock %}
                    {% block header_img %}<img class="slide-image" src="{{ asset('assets/img/todolist_homepage.jpg') }}" alt="todo list">{% endblock %}
                </div>
            </div>

            <br />

            <div class="row">
                <div class="col-md-12">
                    {% block body %}{% endblock %}
                </div>
            </div>
        </div>
        <!-- /.container -->

        <div class="container">

            <hr>
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p class="pull-right">Copyright &copy; OpenClassrooms</p>
                    </div>
                </div>
            </footer>

        </div>
        <script src="{{ asset('assets/js/jquery.js') }}"></script>
        <script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
    </body>
</html>